apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app-05
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: app4
  filterTags:
    pattern: "^[a-f0-9]+-(?P<ts>[0-9]*)$"
    extract: "$ts"
  policy:
    numerical:
      order: asc
